### ISSUE TITLE
I have a problem to download the data from OpenCap!!

### ISSUE THREAD

**Issue by Ting-Anna** [stanfordnmbl/opencap-core#25]

**Comment by Ting-Anna** [comment]
Once I click download data, the website change to other page that shows file not find error, but the data is successfully show on OpenCap.

**Comment by antoinefalisse** [comment]
Hey, thanks for reporting. I had no problems downloading data (I just tried). It might helpful to share your session ID so that we can take a look (most likely next week). Feel free to send it over privately by email (afalisse@stanford.edu).

FYI you can also download OpenCap data using our scripts. More info here: https://github.com/stanfordnmbl/opencap-processing#download-opencap-data

**Comment by antoinefalisse** [comment]
Hi, I clicked on download data and it downloaded the data. It took a while to start downloading because it is a big folder (>4gb). You might just want to wait.
